# Generated by Django 5.2.8 on 2025-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Email único do colaborador', max_length=254, unique=True)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
