# Generated by Django 5.2.8 on 2025-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_equipamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="funcao",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
