# Generated by Django 5.2.8 on 2025-11-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colaborador_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade emprestada')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('data_prazo', models.DateTimeField(verbose_name='Data de Devolução Prevista')),
                ('estoque_disponivel', models.PositiveIntegerField(default=0, help_text='Quantidade disponível no estoque após empréstimo')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipamento', verbose_name='Equipamento')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.colaborador', verbose_name='Colaborador')),
            ],
        ),
    ]
