# Generated by Django 5.2.8 on 2025-11-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprestimos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='equipamento',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Emprestimos',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
