# Generated by Django 5.2.8 on 2025-11-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade emprestada')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('data_prazo', models.DateTimeField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Real')),
                ('estoque_disponivel', models.PositiveIntegerField(default=0, help_text='Quantidade disponível no estoque após empréstimo')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido')], default='EMPRESTADO', max_length=20, verbose_name='Status')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
        ),
    ]
